
    - name: Add OpenJDK repository
      apt_repository: repo="ppa:openjdk-r/ppa" update_cache=yes
      become: yes
      tags:
      - java
      - development

    - name: Install OpenJDK 8
      apt: pkg=openjdk-8-jre
      become: yes
      tags:
      - java
      - development

    - name: Add Oracle Java repository
      apt_repository: repo='ppa:webupd8team/java' update_cache=yes
      become: yes
      tags:
      - java
      - development

    - name: Accept Oracle Java license
      debconf: name={{ item }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      become: yes
      with_items:
      - oracle-java7-installer
      - oracle-java8-installer
      tags:
      - java
      - development

    - name: Create oracle java cache directories
      file: dest=/var/cache/{{ item }} state=directory
      become: yes
      with_items:
      - oracle-jdk7-installer
      - oracle-jdk8-installer
      tags:
      - java
      - development


    - name: Copy .tar.gz files for oracle java
      get_url: url={{ item.url }} dest=/var/cache/{{ item.cache_directory }}/{{ item.archive }}
      become: yes
      with_items:
      - { url: "https://www.dropbox.com/s/jq0b2wugzx1n494/jdk-7u80-linux-x64.tar.gz?dl=1", archive: "jdk-7u80-linux-x64.tar.gz", cache_directory: oracle-jdk7-installer }
      - { url: "https://www.dropbox.com/s/w4wfyvfnpcyfv6n/jdk-8u144-linux-x64.tar.gz?dl=1", archive: "jdk-8u144-linux-x64.tar.gz", cache_directory: oracle-jdk8-installer }
      tags:
      - java
      - development

    - name: Install Oracle Java
      apt: pkg={{ item }}
      become: yes
      with_items:
      - oracle-java7-installer
      - oracle-java8-installer
      tags:
      - java
      - development

    - name: Install Maven 3
      apt: pkg=maven
      become: yes
      tags:
      - java
      - development
